engines:
  duplications:
    enabled: false
    config:
      languages:
        #mass_threshold: 30
        - javascript
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
ratings:

languages:
  JavaScript: true
exclude_paths:
- "src/public
- .gitignore
- .eslintignore
- .travis.yml
- .eslintrc.json
- "src/__tests__/components/__snapshots__"
- "webpack.config.js"
- "webpack.deployment.config.js"
- "server.js"
- "coverage"