engines:
  duplications:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    config:
      languages:
        JavaScript: true
ratings:
  paths:
      - "src/js"
exclude_paths:
- "public"
- .gitignore
- .eslintignore
- .travis.yml
- .eslintrc.json
- "src/js/__tests__"
- "src/js/__mocks__"
- "webpack.config.js"
- "webpack.deployment.config.js"
- "server.js"
- "coverage"